version: '3.2'

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      # The JMX broker listens on port 61616 and the Web Console on port 8161.
      - 61616:61616
      - 8161:8161

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: Frontend

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: Backend
